# render.yaml
databases:
  - name: activitysync-db
    plan: free

services:
  # --- Backend ---
  - type: web
    name: activitysync-api
    env: python
    plan: free
    rootDir: server
    buildCommand: |                 # | preserves newlines
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: >                 # > turns single newlines into spaces
      gunicorn main:app
      -k uvicorn.workers.UvicornWorker 
      -w 2
      -b 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: activitysync-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: ALLOWED_ORIGINS
        value: https://activitysync-client.onrender.com
      - key: FRONTEND_URL
        value: https://activitysync-client.onrender.com
      - key: BACKEND_URL
        value: https://activitysync-api.onrender.com
      - key: BACKEND_DOMAIN
        value: activitysync-api.onrender.com
      - key: SESSION_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: STRAVA_CLIENT_ID
        sync: false
      - key: STRAVA_CLIENT_SECRET
        sync: false
      - key: STRAVA_VERIFY_TOKEN
        generateValue: true

  # --- Front-end ---
  - type: web
    name: activitysync-client
    env: static
    rootDir: client
    buildCommand: |
      npm ci
      npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL              # client hits the backend
        value: https://activitysync-api.onrender.com