name: Activity Sync CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: activity_sync
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
        ports: ['5432:5432']

    env:
      NODE_ENV: test
      PYTHONPATH: .
      DATABASE_URL: postgresql://user:pass@localhost:5432/activity_sync


    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./server

      - name: Run backend tests
        run: |
            pytest
        working-directory: ./server